### ISSUE TITLE
Add a printer-oriented stylesheet

### ISSUE THREAD

**Issue by nodiscc** [owncloud/tasks#119]
It would be very nice to be able to print tasks in a "printer-friendly" way (only print tasks contents, not UI elements as it is currently; try to do a print preview on the tasks page)

I believe it can be done by defining a stylesheet specifically for printed media with eg. `<link rel="stylesheet" href="print.css" type="text/css" media="print" />`. The print view should only contain checkboxes and the tasks text., and aim to minimize paper loss (2 column layout?)

@raimund-schluessler are you interested in this change?

**Comment by raimund-schluessler** [comment]
I guess this would be nice to have (although I never felt the need to print my tasks list ;). Should be relatively easy as you just said.

**Comment by nodiscc** [comment]
Adding these styles manually seems to do the trick

```css
body {
  font-family: "Open Sans";
}

ol {
  list-style-type: circle;
  
}

#update-notification a, .section, #task-details, #slideshow, #header, #app-navigation, #add-task, .loadmore {
  display: none;
}

.duedate {
  color: #666;
  background-color: #EEE;
  float: left;
  font-family: "Consolas";
  padding: 0 3px 0 3px;
  margin: 0 3px 0 0;
  border-radius: 2px;
}

.overdue {
  color: #f44
}
```

However I'm not sure how to force printers to use this, I have to check how to use CSS Media Types http://www.w3schools.com/css/css_mediatypes.asp
